AWSTemplateFormatVersion: 2010-09-09

Description:
  Learning basic of CloudFormation.
  This stack will create EC2 Instance.

Parameters:

  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small

Resources:

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0a8b4cd432b1c3063
      InstanceType: !Ref InstanceType

Outputs:

  EC2InstanceIP:
    Description: IP Address of EC2 Instance create by this Coludformation stack.
    Value: !GetAtt EC2Instance.PublicIp

  EC2InstanceAvailabilityZone:
    Description: AvailabilityZone of EC2 Instance create by this Coludformation stack.
    Value: !GetAtt EC2Instance.AvailabilityZone